[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install && npm run init-db"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "$PORT"

[[services]]
name = "cultureon-backend"
root = "backend"

[[services.healthcheck]]
path = "/health"
interval = 30
timeout = 5
maxRetries = 3